AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Try Using Extension

Parameters:
  GroupName:
    Type: 'String'
    Default: TestGroup2

  GroupDescription:
    Type: 'String'
    Default: TestGroup2_description

  AppClientId:
    Type: 'String'
    Default: xxxxxxxxx

  AppAPIToken:
    Type: 'String'
    Default: xxxxxxx

  TenantId:
    Type: 'String'
    Default: xxxxxx

Resources:
  SampleEvent:
    Type: Dotmatics::AzureAD::Group
    Properties:
      GroupName: !Ref GroupName
      GroupType: SECURITY
      GroupDescription: !Ref GroupDescription
      Owners:
        - OwnerType: USER
          Name: AlexW@qkdw.onmicrosoft.com
#        - OwnerType: USER
#          Name: xxxxxx@xxxxxx.onmicrosoft.com
#        - OwnerType: USER
#          Name: xxxxxxx@xxxxxx.onmicrosoft.com

      CredentialAppClientId: !Ref AppClientId
      CredentialAppAPIToken: !Ref AppAPIToken
      CredentialTenantId:    !Ref TenantId

Outputs:
  GroupID:
    Value: !GetAtt SampleEvent.GroupId
  GeneratedId:
    Value: !GetAtt SampleEvent.GeneratedId