AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Try Using Extension
Resources:

  SampleEvent:
    Type: Dotmatics::AzureAD::Group
    Properties:
      GroupName: TestGroup2
      GroupType: SECURITY
      GroupOwnerAppName: Test
      CredentialAppClientId: "xxxxxxxxx"
      CredentialAppAPIToken: "xxxxxxxxx"
      CredentialTenantId:    "xxxxxxxx"

Outputs:
  GroupID:
    Value: !GetAtt SampleEvent.GroupId
  GeneratedId:
    Value: !GetAtt SampleEvent.GeneratedId