AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Try Using Extension

Resources:

  SampleEvent:
    Type: Dotmatics::SSO::GroupInfo
    Properties:
      GroupName: "AWSAccountFactory"
      IdentityStoreId: "d-9c67127909"