name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry --version
          poetry install --no-root

      - name: Static Analysis and Code Formatting
        run: |
          echo "Running mypy"
          mypy src/
          echo "Running flake8"
          flake8 --max-line-length 120 src/
          echo "Running black"
          black src/ -l 120 --check

      - name: Unit Tests
        run: |
          echo "Running pytest"   
          pytest  --cov-branch --cov=src/ tests/ --log-cli-level=DEBUG --junit-xml=junit.xml --cov-report=xml --cov-report=html:ci_coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODE_COV }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true